#pragma once

template <class T>
class CProxy_IWebUIEvents : public IConnectionPointImpl<T, &__uuidof(_IWebUIEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
